import type { InterviewQuestion } from "@/lib/types"

const quizQuestions: InterviewQuestion[] = [
  {
    id: "sd-quiz-01",
    tech: "system-design",
    question: "Your single server is maxing out at 10,000 req/sec. What is the most scalable long-term solution?",
    shortAnswer: "Horizontal scaling — add more servers behind a load balancer. No ceiling, adds redundancy, cost-efficient with auto-scaling.",
    answer: "Horizontal scaling with a load balancer has no theoretical ceiling and eliminates the single point of failure. Vertical scaling hits a hardware ceiling and remains a single point of failure.",
    options: [
      "Add more servers behind a load balancer (horizontal scaling)",
      "Upgrade to the largest available server (vertical scaling)",
      "Add more RAM to the existing server",
      "Switch from REST to GraphQL to reduce payload size",
    ],
    difficulty: "beginner",
    tags: ["scaling", "load-balancing"],
  },
  {
    id: "sd-quiz-02",
    tech: "system-design",
    question: "A user's profile is read 50,000 times per day but updated once per week. What should you do?",
    shortAnswer: "Cache the profile in Redis with a TTL. Serves reads in <1ms from memory instead of querying the DB 50,000 times a day.",
    answer: "High read frequency + low update frequency = perfect caching candidate. Cache the profile in Redis; set a TTL or explicitly bust the cache key when the profile is updated.",
    options: [
      "Cache the profile in Redis with a TTL",
      "Add an index to the users table",
      "Replicate the database",
      "Move user profiles to a NoSQL database",
    ],
    difficulty: "beginner",
    tags: ["caching", "redis"],
  },
  {
    id: "sd-quiz-03",
    tech: "system-design",
    question: "In the CAP theorem, which two properties does Cassandra prioritize?",
    shortAnswer: "Availability and Partition Tolerance (AP). Cassandra is always available but offers eventual consistency — a read may briefly return stale data after a write.",
    answer: "Cassandra is an AP system: it remains available and partition-tolerant but sacrifices strict consistency. Reads may briefly return stale data — this is called eventual consistency.",
    options: [
      "Availability and Partition Tolerance (AP)",
      "Consistency and Partition Tolerance (CP)",
      "Consistency and Availability (CA)",
      "All three — CAP theorem doesn't apply to Cassandra",
    ],
    difficulty: "intermediate",
    tags: ["cap-theorem", "cassandra", "consistency"],
  },
  {
    id: "sd-quiz-04",
    tech: "system-design",
    question: "Why must message queue consumers be idempotent?",
    shortAnswer: "Message queues guarantee at-least-once delivery — a message can be delivered more than once. Idempotent consumers produce the same result whether the message is processed once or ten times.",
    answer: "At-least-once delivery is the standard queue guarantee. If a consumer crashes after processing but before acknowledging, the broker redelivers. Processing twice must equal processing once (idempotent), or you get duplicate emails, double charges, etc.",
    options: [
      "Because messages can be delivered more than once (at-least-once delivery)",
      "Because queues process messages out of order",
      "Because consumers must be faster than producers",
      "Because queues delete messages before consumers read them",
    ],
    difficulty: "intermediate",
    tags: ["message-queues", "idempotency", "reliability"],
  },
  {
    id: "sd-quiz-05",
    tech: "system-design",
    question: "What is the main advantage of consistent hashing over modular hashing (key % N) when adding servers?",
    shortAnswer: "Only 1/N of keys need to move. Modular hashing remaps nearly all keys when N changes, causing a cache stampede.",
    answer: "When you add a server to a pool of N servers, modular hashing requires remapping almost every key (since key % (N+1) ≠ key % N for most keys). Consistent hashing only moves ~1/N of total keys to the new server.",
    options: [
      "Only 1/N of keys need to be remapped when a server is added or removed",
      "It distributes keys more evenly across servers",
      "It requires no knowledge of how many servers exist",
      "It supports unlimited server additions without any key movement",
    ],
    difficulty: "advanced",
    tags: ["consistent-hashing", "distributed-systems"],
  },
  {
    id: "sd-quiz-06",
    tech: "system-design",
    question: "Which rate limiting algorithm allows controlled bursting above the average rate?",
    shortAnswer: "Token Bucket — tokens accumulate up to a bucket capacity, allowing a burst when the bucket is full, then rate-limited to the refill rate.",
    answer: "Token Bucket refills at a fixed rate but allows consuming multiple tokens at once up to bucket capacity. A user who hasn't used the API for a while has a full bucket and can burst. Fixed Window and Sliding Window both enforce a strict per-window limit with no burst allowance.",
    options: [
      "Token Bucket",
      "Fixed Window",
      "Sliding Window",
      "Leaky Bucket",
    ],
    difficulty: "intermediate",
    tags: ["rate-limiting", "token-bucket"],
  },
  {
    id: "sd-quiz-07",
    tech: "system-design",
    question: "A payment service calls 5 downstream APIs synchronously. What is the main risk?",
    shortAnswer: "Cascading failures — if any one API is slow or down, the entire payment request fails or times out, potentially leaving the user in an inconsistent state.",
    answer: "Synchronous chaining means one slow or failed service blocks and fails the entire chain. This is called a cascading failure. The fix is circuit breakers, timeouts, and making non-critical steps asynchronous.",
    options: [
      "Cascading failures — one slow API blocks and fails the entire request",
      "The APIs cannot share the same database",
      "Synchronous calls cannot be retried",
      "Response payload becomes too large",
    ],
    difficulty: "intermediate",
    tags: ["sync", "async", "reliability", "microservices"],
  },
  {
    id: "sd-quiz-08",
    tech: "system-design",
    question: "What is database sharding?",
    shortAnswer: "Sharding splits a table's rows across multiple independent database instances (shards) using a shard key. Each shard holds a subset of data, distributing both storage and write load.",
    answer: "Sharding is horizontal partitioning — splitting rows across multiple DB instances. E.g., users 1-1M on Shard A, 1M-2M on Shard B. Unlike read replicas (which duplicate data), shards each hold unique data and increase write capacity.",
    options: [
      "Splitting rows across multiple database instances using a shard key",
      "Copying the database to multiple read replicas",
      "Compressing database tables to reduce storage",
      "Splitting a database into separate tables by column",
    ],
    difficulty: "advanced",
    tags: ["sharding", "database", "partitioning"],
  },
  {
    id: "sd-quiz-09",
    tech: "system-design",
    question: "A social app has users in 50 countries. Images load in 5ms for US users but 2,000ms for users in Southeast Asia. What is the most effective fix?",
    shortAnswer: "Deploy a CDN. Edge servers cache images near users in Southeast Asia, reducing latency from 2000ms to <20ms without touching the origin infrastructure.",
    answer: "A CDN places cached copies of static content (images, video, JS) on edge servers close to users worldwide. Southeast Asian users get served from a nearby edge node instead of a US-based origin server.",
    options: [
      "Use a CDN to cache images at edge servers near users",
      "Compress images to reduce file size",
      "Add more API servers in the US",
      "Switch to a faster database",
    ],
    difficulty: "beginner",
    tags: ["cdn", "latency", "global", "performance"],
  },
  {
    id: "sd-quiz-10",
    tech: "system-design",
    question: "You need to choose a database for a write-heavy time-series workload: 500M events/day, simple queries by user_id + timestamp. What do you pick?",
    shortAnswer: "Apache Cassandra — designed specifically for write-heavy, time-series workloads with simple access patterns. PostgreSQL would struggle at 500M rows/day without significant sharding effort.",
    answer: "Cassandra's wide-column model with partition key + clustering key is ideal for this pattern. It scales writes linearly by adding nodes. PostgreSQL handles complex queries but struggles at this write volume on a single node.",
    options: [
      "Apache Cassandra — built for write-heavy time-series at scale",
      "PostgreSQL — reliable and ACID-compliant",
      "MongoDB — flexible document schema",
      "MySQL — widely supported and fast for reads",
    ],
    difficulty: "intermediate",
    tags: ["cassandra", "nosql", "database", "time-series"],
  },
  {
    id: "sd-quiz-11",
    tech: "system-design",
    question: "In a URL shortener, why is Base62 encoding preferred over a random hash for generating short codes?",
    shortAnswer: "Base62 encoding of an auto-increment ID guarantees uniqueness without collision checking, produces URL-safe characters, and is shorter than hashes for the same number of unique codes.",
    answer: "Auto-increment ID encoded in Base62 (0-9, a-z, A-Z) is guaranteed unique because the ID is unique. A hash of the URL can collide (two different URLs produce the same hash prefix), requiring a collision check loop. Base62 is also URL-safe (unlike Base64 which includes + and /).",
    options: [
      "Auto-increment IDs encoded in Base62 are guaranteed unique with no collision risk",
      "Base62 produces shorter codes than any other encoding",
      "Base62 is faster to compute than MD5 hashing",
      "Hashes are not URL-safe",
    ],
    difficulty: "intermediate",
    tags: ["url-shortener", "base62", "hashing", "id-generation"],
  },
  {
    id: "sd-quiz-12",
    tech: "system-design",
    question: "What should you do FIRST at the start of a system design interview?",
    shortAnswer: "Clarify requirements — ask about scale (QPS, users, data volume), functional requirements, and constraints. Never design without knowing what you're designing for.",
    answer: "Jumping straight to architecture is the most common mistake in system design interviews. Requirements determine everything: whether to use SQL or NoSQL, whether you need a cache, what scale the system must handle. Estimate first, design second.",
    options: [
      "Clarify requirements and estimate scale (QPS, storage, users)",
      "Draw the high-level architecture diagram immediately",
      "Choose the database technology",
      "Define the API endpoints",
    ],
    difficulty: "beginner",
    tags: ["interview", "system-design", "requirements"],
  },
]

export default quizQuestions
