import type { Roadmap } from "@/lib/types"

const frontendRoadmap: Roadmap = {
  id: "frontend",
  role: "Frontend Developer",
  title: "Frontend Developer",
  tagline: "From zero to hireable in one roadmap",
  description:
    "Every node is ordered by dependency, weighted by interview frequency, and linked to a real lesson. This isn't a poster — it's a curriculum you can actually follow.",
  icon: "🖥️",
  color: "#00d992",
  totalHours: 120,
  nodes: [
    // ── Web Foundations ──────────────────────────────────────────────
    {
      id: "internet-basics",
      title: "How the Internet Works",
      description:
        "DNS, HTTP/HTTPS, TCP/IP, browsers, request-response cycle. What actually happens when you type a URL.",
      why: "Every bug you'll ever debug touches the network. You can't reason about loading states, CORS errors, or slow APIs without this mental model.",
      priority: "essential",
      interviewWeight: 3,
      estimatedHours: 4,
      prerequisites: [],
      tags: ["http", "dns", "networking", "browser"],
      position: { x: 280, y: 0 },
    },
    {
      id: "html",
      title: "HTML Fundamentals",
      description:
        "Semantic elements, forms, accessibility attributes, the DOM tree. HTML is the skeleton of everything you build.",
      why: "Interviewers still ask 'what's the difference between div and section?' — and more importantly, bad HTML breaks screen readers and SEO.",
      priority: "essential",
      interviewWeight: 3,
      estimatedHours: 8,
      prerequisites: ["internet-basics"],
      tags: ["html", "semantic", "dom", "accessibility"],
      position: { x: 40, y: 160 },
    },
    {
      id: "css",
      title: "CSS Fundamentals",
      description:
        "The box model, flexbox, grid, positioning, specificity, responsive design, and CSS variables.",
      why: "CSS is deceptively hard. The box model and specificity are behind 80% of visual bugs. Flexbox and Grid are asked in every frontend screen.",
      priority: "essential",
      interviewWeight: 4,
      estimatedHours: 12,
      prerequisites: ["internet-basics"],
      tags: ["css", "flexbox", "grid", "responsive", "box-model"],
      position: { x: 520, y: 160 },
    },
    {
      id: "js-fundamentals",
      title: "JavaScript Core",
      description:
        "Variables, data types, functions, scope, closures, prototypes, the event loop, and the call stack.",
      why: "JavaScript is the only language that runs in the browser. Without a solid understanding of closures and the event loop, you will write bugs you cannot explain.",
      priority: "essential",
      interviewWeight: 5,
      estimatedHours: 20,
      prerequisites: ["html", "css"],
      tags: ["javascript", "closures", "scope", "event-loop", "prototypes"],
      position: { x: 280, y: 320 },
    },
    // ── JavaScript Deeper ─────────────────────────────────────────────
    {
      id: "dom-events",
      title: "DOM & Browser Events",
      description:
        "Querying the DOM, event listeners, event bubbling, delegation, and preventing defaults.",
      why: "React abstracts the DOM — but when something breaks, you debug real DOM events. Also the foundation for understanding how React's synthetic event system works.",
      priority: "essential",
      interviewWeight: 3,
      estimatedHours: 6,
      prerequisites: ["js-fundamentals"],
      linkedLessonPath: "/react/learn/beginner/00c-event-handling",
      tags: ["dom", "events", "bubbling", "delegation"],
      position: { x: 40, y: 480 },
    },
    {
      id: "es6-modern",
      title: "ES6+ Modern JavaScript",
      description:
        "Arrow functions, destructuring, spread/rest, optional chaining, modules (import/export), template literals, and nullish coalescing.",
      why: "All modern React code is written in ES6+. If you don't know destructuring, you'll misread React props. If you don't know modules, you'll misread every import.",
      priority: "essential",
      interviewWeight: 4,
      estimatedHours: 8,
      prerequisites: ["js-fundamentals"],
      tags: ["es6", "arrow-functions", "destructuring", "modules", "spread"],
      position: { x: 520, y: 480 },
    },
    {
      id: "async-js",
      title: "Async JavaScript",
      description:
        "Callbacks, Promises, async/await, the Fetch API, and error handling with try/catch.",
      why: "Every real app fetches data. Race conditions, loading states, and error handling all depend on understanding how async code actually executes in JS.",
      priority: "essential",
      interviewWeight: 5,
      estimatedHours: 10,
      prerequisites: ["dom-events", "es6-modern"],
      tags: ["async", "promises", "await", "fetch", "api"],
      position: { x: 280, y: 640 },
    },
    // ── Dev Tools ─────────────────────────────────────────────────────
    {
      id: "git",
      title: "Git & GitHub",
      description:
        "Init, add, commit, push, pull, branching, merging, rebasing, and resolving conflicts.",
      why: "Every job uses Git. You'll be asked to fix a merge conflict in your first week. You need this before any collaborative project.",
      priority: "essential",
      interviewWeight: 3,
      estimatedHours: 6,
      prerequisites: ["async-js"],
      tags: ["git", "github", "version-control", "branches"],
      position: { x: 40, y: 800 },
    },
    {
      id: "npm",
      title: "Package Managers & Bundlers",
      description:
        "npm/yarn/pnpm, package.json, node_modules, semver, Vite, and how bundlers transform your code.",
      why: "You can't use React without npm. Understanding what bundlers do explains why your production build is fast while dev is live-reloading.",
      priority: "essential",
      interviewWeight: 2,
      estimatedHours: 4,
      prerequisites: ["async-js"],
      tags: ["npm", "yarn", "vite", "bundler", "package-json"],
      position: { x: 520, y: 800 },
    },
    // ── React ─────────────────────────────────────────────────────────
    {
      id: "react-jsx",
      title: "React & JSX",
      description:
        "What React is, how JSX compiles, the virtual DOM, creating your first component, and rendering rules.",
      why: "You cannot write a single line of React without understanding JSX. This is the foundation everything else builds on — and className vs class trips up beginners in every interview.",
      priority: "essential",
      interviewWeight: 4,
      estimatedHours: 5,
      prerequisites: ["git", "npm"],
      linkedLessonPath: "/react/learn/beginner/00-what-is-jsx",
      tags: ["react", "jsx", "virtual-dom", "components"],
      position: { x: 280, y: 960 },
    },
    {
      id: "components-props",
      title: "Components & Props",
      description:
        "Functional components, props drilling, children, prop types, and how to split a UI into reusable pieces.",
      why: "The entire React mental model is 'UI = f(props)'. Get this wrong and you'll pass state everywhere, create spaghetti, and fail every React question.",
      priority: "essential",
      interviewWeight: 4,
      estimatedHours: 5,
      prerequisites: ["react-jsx"],
      linkedLessonPath: "/react/learn/beginner/00b-components-and-props",
      tags: ["components", "props", "reusability", "composition"],
      position: { x: 40, y: 1120 },
    },
    {
      id: "state-usestate",
      title: "State with useState",
      description:
        "Local component state, why plain variables don't trigger re-renders, state updates are async, and lifting state up.",
      why: "useState is the most common React interview topic. 'Why doesn't my variable update the UI?' is the #1 beginner bug — and the answer is useState.",
      priority: "essential",
      interviewWeight: 5,
      estimatedHours: 6,
      prerequisites: ["react-jsx"],
      linkedLessonPath: "/react/learn/beginner/01-the-dashboard-crisis",
      tags: ["useState", "state", "re-render", "hooks"],
      position: { x: 520, y: 1120 },
    },
    {
      id: "useeffect",
      title: "Side Effects with useEffect",
      description:
        "Running code after render, the dependency array, cleanup functions, and avoiding infinite loops.",
      why: "useEffect is the most misused hook. The infinite loop bug, missing dependencies, and stale closures all come from not understanding how it works.",
      priority: "essential",
      interviewWeight: 5,
      estimatedHours: 6,
      prerequisites: ["components-props", "state-usestate"],
      linkedLessonPath: "/react/learn/beginner/02-the-infinite-loop",
      tags: ["useEffect", "side-effects", "lifecycle", "cleanup"],
      position: { x: 40, y: 1280 },
    },
    {
      id: "usecontext",
      title: "Context API",
      description:
        "createContext, Provider, useContext, and when to use context vs prop drilling vs state management.",
      why: "Context solves prop drilling — passing data through 5 layers of components. It's the bridge between local state and a full state manager, and asked in every senior React interview.",
      priority: "essential",
      interviewWeight: 4,
      estimatedHours: 4,
      prerequisites: ["useeffect"],
      linkedLessonPath: "/react/learn/beginner/03-prop-drilling-nightmare",
      tags: ["useContext", "context", "prop-drilling", "provider"],
      position: { x: 520, y: 1280 },
    },
    {
      id: "advanced-hooks",
      title: "useMemo, useCallback & useRef",
      description:
        "Memoizing expensive calculations, stabilizing function references, accessing DOM nodes, and avoiding unnecessary re-renders.",
      why: "These separate React developers from React engineers. Without useMemo and useCallback, your app re-renders on every keystroke. Without useRef, you can't access the DOM.",
      priority: "essential",
      interviewWeight: 4,
      estimatedHours: 6,
      prerequisites: ["useeffect", "usecontext"],
      linkedLessonPath: "/react/learn/beginner/04-the-slow-list",
      tags: ["useMemo", "useCallback", "useRef", "performance", "memoization"],
      position: { x: 280, y: 1440 },
    },
    // ── Tooling & Ecosystem ───────────────────────────────────────────
    {
      id: "typescript",
      title: "TypeScript Basics",
      description:
        "Types, interfaces, generics, type inference, and how to type React components and hooks.",
      why: "90% of production React codebases use TypeScript. It catches bugs before runtime and makes refactoring safe. It will be in every job listing you see.",
      priority: "essential",
      interviewWeight: 4,
      estimatedHours: 10,
      prerequisites: ["advanced-hooks"],
      tags: ["typescript", "types", "interfaces", "generics"],
      position: { x: 40, y: 1600 },
    },
    {
      id: "react-router",
      title: "React Router",
      description:
        "Client-side routing, nested routes, route params, navigation hooks, and protected routes.",
      why: "Every multi-page React app uses a router. Without it, the browser reloads on navigation — destroying your app state and user experience.",
      priority: "essential",
      interviewWeight: 3,
      estimatedHours: 5,
      prerequisites: ["advanced-hooks"],
      tags: ["react-router", "routing", "navigation", "spa"],
      position: { x: 520, y: 1600 },
    },
    {
      id: "css-tooling",
      title: "CSS Tooling (Tailwind)",
      description:
        "Utility-first CSS with Tailwind, CSS Modules, responsive design utilities, and design systems.",
      why: "Tailwind is now the default CSS approach at most startups. Writing raw CSS for every project doesn't scale — utility classes keep teams consistent and fast.",
      priority: "good-to-know",
      interviewWeight: 3,
      estimatedHours: 5,
      prerequisites: ["advanced-hooks"],
      tags: ["tailwind", "css-modules", "design-system", "styling"],
      position: { x: 280, y: 1760 },
    },
    {
      id: "state-management",
      title: "State Management (Zustand)",
      description:
        "Global state without Redux boilerplate, Zustand stores, slices, persistence, and when NOT to use global state.",
      why: "When Context gets complex — multiple consumers, frequent updates — you need a real state manager. Zustand is the modern choice: minimal API, no boilerplate, works with TypeScript.",
      priority: "good-to-know",
      interviewWeight: 3,
      estimatedHours: 6,
      prerequisites: ["typescript", "react-router"],
      tags: ["zustand", "redux", "global-state", "store"],
      position: { x: 40, y: 1920 },
    },
    {
      id: "testing",
      title: "Testing (Jest + RTL)",
      description:
        "Unit tests with Jest, component testing with React Testing Library, and the philosophy of testing behavior not implementation.",
      why: "Untested code is technical debt. Companies with CI/CD pipelines require tests. React Testing Library's 'test what the user sees' approach is now the industry standard.",
      priority: "good-to-know",
      interviewWeight: 3,
      estimatedHours: 8,
      prerequisites: ["typescript"],
      tags: ["testing", "jest", "react-testing-library", "unit-tests"],
      position: { x: 520, y: 1920 },
    },
    // ── Production ────────────────────────────────────────────────────
    {
      id: "nextjs",
      title: "Next.js",
      description:
        "App Router, Server Components, server-side rendering, static generation, API routes, and full-stack React.",
      why: "Next.js is the industry standard for production React. It solves SEO, performance, and routing. Most React job listings mention Next.js specifically.",
      priority: "essential",
      interviewWeight: 4,
      estimatedHours: 12,
      prerequisites: ["state-management", "testing"],
      tags: ["nextjs", "ssr", "app-router", "full-stack", "react"],
      position: { x: 280, y: 2080 },
    },
    {
      id: "web-performance",
      title: "Web Performance",
      description:
        "Core Web Vitals, lazy loading, code splitting, image optimization, and how browsers render.",
      why: "Performance is a feature. Google ranks slow sites lower. Interviewers ask about LCP, CLS, and FID in senior roles. 'It works on my machine' is not enough.",
      priority: "good-to-know",
      interviewWeight: 3,
      estimatedHours: 6,
      prerequisites: ["nextjs"],
      tags: ["performance", "core-web-vitals", "lazy-loading", "optimization"],
      position: { x: 40, y: 2240 },
    },
    {
      id: "accessibility",
      title: "Accessibility (a11y)",
      description:
        "ARIA roles, keyboard navigation, focus management, screen reader testing, and WCAG guidelines.",
      why: "Accessibility is legally required in many countries and morally correct. Inaccessible UIs lock out 15% of users. Senior roles always ask about it.",
      priority: "good-to-know",
      interviewWeight: 2,
      estimatedHours: 5,
      prerequisites: ["nextjs"],
      tags: ["accessibility", "aria", "wcag", "a11y", "keyboard"],
      position: { x: 520, y: 2240 },
    },
  ],

  edges: [
    // Foundations
    { id: "e1", source: "internet-basics", target: "html", why: "HTML documents are served over HTTP — you need to understand what a request/response is before you start building pages." },
    { id: "e2", source: "internet-basics", target: "css", why: "CSS files are loaded by the browser as separate HTTP requests. Understanding caching and MIME types helps you debug why styles don't update." },
    { id: "e3", source: "html", target: "js-fundamentals", why: "JavaScript runs inside HTML pages and manipulates the DOM. Without HTML structure, there's nothing for JS to interact with." },
    { id: "e4", source: "css", target: "js-fundamentals", why: "JS frequently reads and modifies CSS properties. You need to know what you're manipulating." },
    // JS deeper
    { id: "e5", source: "js-fundamentals", target: "dom-events", why: "The DOM is built on JavaScript — querying elements with getElementById and handling clicks with addEventListener uses all the JS fundamentals: functions, callbacks, and objects." },
    { id: "e6", source: "js-fundamentals", target: "es6-modern", why: "ES6 is a syntax layer on top of JavaScript fundamentals. You need to understand what a function is before you learn arrow function shorthand." },
    { id: "e7", source: "dom-events", target: "async-js", why: "Event listeners are your first taste of async programming. Fetch API (async) is just a more powerful version of listening for an event that fires later." },
    { id: "e8", source: "es6-modern", target: "async-js", why: "async/await is ES6+ syntax. Promises are ES6. You cannot learn async JS without ES6 first." },
    // Dev tools
    { id: "e9", source: "async-js", target: "git" },
    { id: "e10", source: "async-js", target: "npm", why: "npm scripts and package.json use JavaScript syntax. Async concepts appear in build tools constantly." },
    // React basics
    { id: "e11", source: "git", target: "react-jsx", why: "React projects are Git repositories. You need to be able to clone, commit, and push before starting any React project with others." },
    { id: "e12", source: "npm", target: "react-jsx", why: "'npm install react' is how React gets into your project. You must understand package managers before you can set up a React app." },
    // Hooks
    { id: "e13", source: "react-jsx", target: "components-props", why: "Components ARE JSX functions. You learn what JSX compiles to, then you learn how to structure those functions as reusable components." },
    { id: "e14", source: "react-jsx", target: "state-usestate", why: "State only makes sense once you understand rendering. JSX + re-rendering is the setup; useState is the trigger." },
    { id: "e15", source: "components-props", target: "useeffect", why: "useEffect runs after component renders. You need to know how component rendering works (via props) before understanding when useEffect fires." },
    { id: "e16", source: "state-usestate", target: "useeffect", why: "The most common useEffect pattern is fetching data when state changes. You need useState to manage the fetched data." },
    { id: "e17", source: "useeffect", target: "usecontext", why: "Context is often fetched in useEffect (auth state, user data). Learn the tool before the pattern that uses it." },
    { id: "e18", source: "useeffect", target: "advanced-hooks", why: "useMemo and useCallback are optimizations for when your useEffect dependency arrays cause too many re-renders." },
    { id: "e19", source: "usecontext", target: "advanced-hooks" },
    // Tooling
    { id: "e20", source: "advanced-hooks", target: "typescript", why: "TypeScript's value shines brightest when typing complex hook patterns. You need to understand hooks before you can type them correctly." },
    { id: "e21", source: "advanced-hooks", target: "react-router", why: "Route transitions re-mount components, which triggers useEffect and can create memory leaks. Know your hooks before introducing routing." },
    { id: "e22", source: "advanced-hooks", target: "css-tooling", why: "Tailwind pairs with component-based architecture — you apply classes on components. Understand components deeply before layering on styling systems." },
    { id: "e23", source: "typescript", target: "state-management", why: "Typed stores (Zustand with TypeScript) are the only kind worth using. TypeScript first, then apply it to state." },
    { id: "e24", source: "react-router", target: "state-management", why: "Global state and routing work together — persisting state across routes requires understanding both." },
    { id: "e25", source: "typescript", target: "testing", why: "Test files in TypeScript are the industry norm. You'll be typing your test utilities and mocks." },
    { id: "e26", source: "css-tooling", target: "nextjs" },
    // Production
    { id: "e27", source: "state-management", target: "nextjs", why: "Server Components in Next.js change how you think about state (server state vs client state). Know client state management cold before adding the server dimension." },
    { id: "e28", source: "testing", target: "nextjs", why: "Testing Server Components and API routes requires different patterns. Learn standard RTL first." },
    { id: "e29", source: "nextjs", target: "web-performance", why: "Core Web Vitals are measured on real production pages. Next.js is how you build those pages — performance optimization is the final layer on top." },
    { id: "e30", source: "nextjs", target: "accessibility", why: "Accessibility in Next.js includes server-rendered HTML semantics, link prefetching focus, and route transitions. Apply a11y to the full stack, not just React components." },
  ],
}

export default frontendRoadmap
