import type { InterviewQuestion } from "@/lib/types"

// Questions optimised for multiple-choice quiz mode.
// options[0] is always the correct answer — shuffle before displaying.
const quizQuestions: InterviewQuestion[] = [
  {
    id: "quiz-01",
    tech: "react",
    question: "What does the useState hook return?",
    shortAnswer: "An array with the current value and a setter function.",
    answer: "useState returns a two-element array: the current state value and a setter function. Calling the setter schedules a re-render with the new value.",
    options: [
      "An array with the current value and a setter function",
      "An object with value and update properties",
      "The current state value only",
      "A Promise that resolves to the state",
    ],
    difficulty: "beginner",
    tags: ["useState", "hooks"],
  },
  {
    id: "quiz-02",
    tech: "react",
    question: "When does useEffect with an empty dependency array [] run?",
    shortAnswer: "Once after the first render (on mount).",
    answer: "An empty dependency array tells React 'this effect has no dependencies' — so it only runs once, after the component mounts. It will not re-run on subsequent renders.",
    options: [
      "Once after the first render (on mount)",
      "After every render",
      "Before the first render",
      "Never — empty array disables the effect",
    ],
    difficulty: "beginner",
    tags: ["useEffect", "hooks"],
  },
  {
    id: "quiz-03",
    tech: "react",
    question: "What is the correct way to attach a click handler that needs an argument?",
    shortAnswer: "Wrap it in an arrow function: onClick={() => handleClick(id)}",
    answer: "onClick={handleClick(id)} calls the function immediately during render and passes its return value as the handler. You must wrap it: onClick={() => handleClick(id)}",
    options: [
      "onClick={() => handleClick(id)}",
      "onClick={handleClick(id)}",
      'onClick="handleClick(id)"',
      "onClick={handleClick, id}",
    ],
    difficulty: "beginner",
    tags: ["events", "onClick"],
  },
  {
    id: "quiz-04",
    tech: "react",
    question: "What attribute do you use instead of HTML's 'class' in JSX?",
    shortAnswer: "className — because 'class' is a reserved keyword in JavaScript.",
    answer: "JSX compiles to JavaScript, so reserved JS keywords like 'class' can't be used as attribute names. React uses 'className' instead, which maps to the DOM's className property.",
    options: [
      "className",
      "class",
      "cssClass",
      "styleClass",
    ],
    difficulty: "beginner",
    tags: ["jsx", "fundamentals"],
  },
  {
    id: "quiz-05",
    tech: "react",
    question: "What does JSX compile to before running in the browser?",
    shortAnswer: "React.createElement() calls — the browser never sees raw JSX.",
    answer: "A compiler (Babel/SWC) transforms JSX into React.createElement() calls before the browser runs the code. For example, <h1>Hello</h1> becomes React.createElement('h1', null, 'Hello').",
    options: [
      "React.createElement() calls",
      "HTML strings",
      "Real DOM nodes",
      "JSON objects",
    ],
    difficulty: "beginner",
    tags: ["jsx", "fundamentals"],
  },
  {
    id: "quiz-06",
    tech: "react",
    question: "Why should you never use array index as a list key?",
    shortAnswer: "Index-based keys break when items are reordered or deleted — React maps the wrong state to the wrong item.",
    answer: "Array index changes when items are added, removed, or reordered. React uses keys to match items across renders. If index shifts, React maps old state (e.g., checked checkboxes) to the wrong item.",
    options: [
      "Reordering or deleting items shifts indexes, causing React to map state to the wrong items",
      "Indexes are not unique enough",
      "React forbids numeric keys",
      "It causes infinite re-renders",
    ],
    difficulty: "beginner",
    tags: ["keys", "lists"],
  },
  {
    id: "quiz-07",
    tech: "react",
    question: "What is the key difference between useMemo and useCallback?",
    shortAnswer: "useMemo caches a computed value; useCallback caches a function reference.",
    answer: "useMemo(() => compute(), [deps]) returns and caches the result of compute(). useCallback(() => fn, [deps]) returns and caches the function itself. Both only recompute when deps change.",
    options: [
      "useMemo caches a computed value; useCallback caches a function reference",
      "useMemo is for async operations; useCallback is for sync",
      "useMemo runs on mount only; useCallback runs on every update",
      "They are identical under the hood",
    ],
    difficulty: "intermediate",
    tags: ["useMemo", "useCallback", "performance"],
  },
  {
    id: "quiz-08",
    tech: "react",
    question: "Mutating a useRef's .current property causes what?",
    shortAnswer: "Nothing — changing .current does NOT trigger a re-render.",
    answer: "Unlike useState, mutating ref.current does not notify React of a change. The component does not re-render. This makes refs useful for values that need to persist but shouldn't drive the UI.",
    options: [
      "No re-render — refs are invisible to React's render cycle",
      "An immediate synchronous re-render",
      "A batched re-render on the next tick",
      "A React warning in development mode",
    ],
    difficulty: "intermediate",
    tags: ["useRef", "hooks"],
  },
  {
    id: "quiz-09",
    tech: "react",
    question: "Which rendering pattern is best for a loading / error / success state?",
    shortAnswer: "Early returns — guard clauses at the top of the component before the main return.",
    answer: "Early returns keep each case isolated and readable. if (loading) return <Spinner />; if (error) return <Error />; then the success JSX at the end. This avoids deeply nested ternaries.",
    options: [
      "Early returns: if (loading) return <Spinner />; if (error) return <Error />;",
      "A single nested ternary covering all three states",
      "Three separate components rendered simultaneously with CSS visibility",
      "useState to track which component to render",
    ],
    difficulty: "beginner",
    tags: ["conditional-rendering", "patterns"],
  },
  {
    id: "quiz-10",
    tech: "react",
    question: "What does React use the Virtual DOM for?",
    shortAnswer: "To diff the new tree against the old one and apply only the minimum real DOM changes needed.",
    answer: "The Virtual DOM is a lightweight JS copy of the real DOM. After a state change, React re-renders the virtual tree, diffs it against the previous snapshot (reconciliation), and applies only the necessary real DOM updates — batching writes to avoid expensive browser repaints.",
    options: [
      "Diff old vs new tree and apply minimum real DOM changes",
      "Render components on the server instead of the client",
      "Store component state between page navigations",
      "Bypass the browser's layout engine for faster rendering",
    ],
    difficulty: "intermediate",
    tags: ["virtual-dom", "reconciliation"],
  },
  {
    id: "quiz-11",
    tech: "react",
    question: "What problem does useContext primarily solve?",
    shortAnswer: "Prop drilling — threading data through components that don't use it just to reach a deeply nested child.",
    answer: "Without Context, sharing data across many levels requires passing props through every intermediate component even if those components don't use the data. Context broadcasts a value that any descendant can read directly.",
    options: [
      "Prop drilling — sharing data without threading it through every level",
      "Expensive re-renders in large component trees",
      "Managing asynchronous state updates",
      "Replacing useState for all state management",
    ],
    difficulty: "beginner",
    tags: ["useContext", "prop-drilling"],
  },
  {
    id: "quiz-12",
    tech: "react",
    question: "When should you create a custom hook?",
    shortAnswer: "When you find the same stateful logic copy-pasted across multiple components — extract it into a function starting with 'use'.",
    answer: "A custom hook extracts reusable hook-based logic the same way a utility function extracts reusable pure logic. If two components share the same useState + useEffect pattern, that's a sign to pull it into a custom hook like useFetch or useLocalStorage.",
    options: [
      "When the same stateful logic is repeated across multiple components",
      "Whenever a component has more than three useState calls",
      "Only when using third-party libraries",
      "To replace Redux in large applications",
    ],
    difficulty: "intermediate",
    tags: ["custom-hooks", "patterns"],
  },
]

export default quizQuestions
